# Generated by Django 2.2.4 on 2022-10-30 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.CharField(default=11111, max_length=5),
            preserve_default=False,
        ),
    ]
