# Generated by Django 2.2.4 on 2022-10-30 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
        ('vendor_app', '0002_address_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='user_app.User'),
            preserve_default=False,
        ),
    ]
